Fixed Lists of Images Not Showing
mozilla/readability pull request #738
Opened 2022-03-09 18:06 UTC by Tuxy222

This change allows for lists of images within the content of the page to be present in reader mode. 

Related to: https://github.com/mozilla/readability/issues/697

2022-03-15 14:51 UTC, niklasbaumgardner requested changes
I just have a few things to address. Thanks for working on this!

2022-03-15 14:51 UTC, niklasbaumgardner commented on Readability.js
> +
nit: We can remove this empty line

2022-03-15 14:51 UTC, niklasbaumgardner commented on Readability.js
> +            if (img > 1 && img <= (li+100)) {
Why do we add 100 to `li` here?

2022-03-15 14:51 UTC, niklasbaumgardner commented on Readability.js
> +            if (img > 1 && img <= (li+100)) {
Why do we add 100 to `li` here?

2022-03-15 14:51 UTC, niklasbaumgardner commented on Readability.js
> +          // Check for lists of images
Instead of having comments on each line, could we have one comment at the beginning explaining why we are doing this check?

2022-03-15 14:51 UTC, niklasbaumgardner commented on Readability.js
> +          // Check for lists of images
Instead of having comments on each line, could we have one comment at the beginning explaining why we are doing this check?

2022-03-23 19:56 UTC, tigleym commented on Readability.js
> +            }
```suggestion
              let child = node.children[x];
              if (child.localName == "li" && child.children.length) {
                  return true;
              }
            li_count = node.getElementsByTagName("li").length;
            if (img > 1 && img <= (li_count)) {
              return false;
            }
```

2022-03-23 19:57 UTC, tigleym requested changes

2022-03-23 19:57 UTC, tigleym commented on Readability.js
> +            }
I think it would be a good idea to document here why we remove some images for this specific case. It's not immediately clear to me here.

2022-03-25 16:58 UTC, tigleym commented
It looks like we have one failing test here. Could you investigate it?

2022-04-20 17:56 UTC, niklasbaumgardner requested changes
I just have a nit to fix. Otherwise, I think this is good

2022-04-20 17:56 UTC, niklasbaumgardner commented on Readability.js
> +            // Don't filter in lists with lis that contain more than one child
```suggestion
            // Don't filter in lists with li's that contain more than one child
```

2022-04-20 17:56 UTC, niklasbaumgardner commented on Readability.js
> +            // Don't filter in lists with lis that contain more than one child
just a nit

2022-04-21 15:49 UTC, tigleym approved these changes
Thank you!

2022-05-04 18:40 UTC, niklasbaumgardner approved these changes

2022-11-18 09:49 UTC, tholu commented
Will this be merged? Or why not?

2022-11-18 10:30 UTC, merged

2022-11-18 10:30 UTC, gijsk commented
I think this just got lost. I just merged it.

2022-11-18 10:30 UTC, gijsk commented
(Thanks for the ping!)