Fix articles showing cookie information in reader mode
mozilla/readability pull request #746
Opened 2022-04-15 07:08 UTC by tthhtao

Applying the `aria-modal` property to an element with `role="dialog"` replaces the technique of using `aria-hidden` in the background. So I think this kind of element should also be considered "invisible" to the reader.

2022-04-21 15:46 UTC, tigleym requested changes
Thanks @tthhtao ! This works nicely, but I think we should address the comment I have here.

2022-04-21 15:46 UTC, tigleym commented on Readability.js
> +        }
This should be added to the check in [isProbablyVisible](https://github.com/tthhtao/readability/blob/2edee0ee6224b9c0ed94f81832cb5e2678d0f0d4/Readability.js#L2206).

2022-05-04 19:14 UTC, tigleym requested changes

2022-05-04 19:14 UTC, tigleym commented on Readability.js
> +      // user can not see element applied with both attribute "aria-modla = true" and "role = dialog"
"arial-modal"

2022-05-04 19:14 UTC, tigleym commented on Readability.js
> +        }
We should remove this check since it should be handled in the one above now

2023-01-19 19:54 UTC, gijsk commented
I think all the review comments were addressed so let's get this merged.

2023-01-19 19:54 UTC, merged

2023-01-19 19:54 UTC, gijsk commented
@tthhtao sorry this sat for such a long time!