fix: jsonld parse is ignored when context url include the trailing slash
mozilla/readability pull request #833
Opened 2024-01-12 02:43 UTC by tianzhich

2024-01-12 16:29 UTC, fchasen requested changes
Thanks for these changes and the test, just some small nits to fix.

2024-01-12 16:29 UTC, fchasen commented on .gitignore
> +.vscode
```suggestion
```
I would recommend adding this to your `~/.gitignore` instead.

2024-01-12 16:29 UTC, fchasen commented on CHANGELOG.md
> +- `isProbablyReaderable` [can now take an optional options object](https://github.com/mozilla/readability/pull/634) to configure it, allowing you to specify the minimum content length, minimum score,
Can you revert this? We'd prefer the line to wrap.

2024-01-12 16:46 UTC, tianzhich commented
> Thanks for these changes and the test, just some small nits to fix.

Hi Fred, Thanks for your time. Now it would be ok.

2024-01-18 21:06 UTC, fchasen approved these changes

2024-01-18 21:07 UTC, merged