Fix missing header from GitLab blog page
mozilla/readability pull request #885
Opened 2024-06-26 21:14 UTC by revolter

2024-06-27 16:23 UTC, fchasen commented
Thanks for submitting the test case and fix, the simpler fix for this seem to be to just remove `tool` from the regex as that doesn't appear to break any other test cases.

2024-06-27 16:24 UTC, revolter commented
Wasn't it added there with a reason? Maybe there is a test case missing for that part of the regex? 🤔

2024-06-27 16:29 UTC, revolter commented
Oh, it's there since [the initial commit](https://github.com/mozilla/readability/commit/55587d91ac5b333ca6bf968e5504f3083c59cf6c#diff-2e165ea528afeb3f92b2bed19888c901d730c559afbbcd821902506eb7b7f9a2R76).

So, should I remove `tool` completely?

2024-06-27 16:33 UTC, fchasen commented
Yep, seems to be fine to remove completely.

2024-06-27 16:33 UTC, fchasen requested changes

2024-06-27 16:33 UTC, fchasen commented on Readability.js
> +    negative: /-ad-|hidden|^hid$| hid$| hid |^hid |banner|combx|comment|com-|contact|foot|footer|footnote|gdpr|masthead|media|meta|outbrain|promo|related|scroll|share|shoutbox|sidebar|skyscraper|spon
```suggestion
    negative: /-ad-|hidden|^hid$| hid$| hid |^hid |banner|combx|comment|com-|contact|foot|footer|footnote|gdpr|masthead|media|meta|outbrain|promo|related|scroll|share|shoutbox|sidebar|skyscraper|sponsor|shopping|tags|widget/i,
```

2024-06-27 23:10 UTC, fchasen approved these changes

2024-06-27 23:11 UTC, merged

2024-06-27 23:13 UTC, fchasen commented
Thanks again for the text case that has most of the text of the header in the id, that pattern doesn't work great with regex matching (for instance if the header was about `Meta`). We may look into this more soon depending on how common that is.

2024-06-28 04:47 UTC, revolter commented
Good job with the contribution instructions 👏🏻 Was thinking about creating an issue at first 😅